"use client";
import { useState } from "react";
import Image from "next/image";
import { BsFillMoonStarsFill, BsSunFill } from "react-icons/bs";
import { FaGithub, FaLinkedin } from "react-icons/fa6";
import profile from "../public/profile.jpeg";
import sky from "../public/sky.png"
import fdm from "../public/fdm.jpg"

const DarkModeSwitcher = ({ darkMode = false, setDarkMode }) => {
  if (darkMode) {
    return <BsFillMoonStarsFill className="text-3xl cursor-pointer" onClick={() => setDarkMode(!darkMode)} />
  } else {
    return <BsSunFill className="text-3xl cursor-pointer text-yellow-500" onClick={() => setDarkMode(!darkMode)} />;
  };
}

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <header>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </header>
      <main className="bg-white px-10 pb-4 dark:bg-gray-900 md:px-20 lg-px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between items-center dark:text-white">
            <h1 className="text-xl">David McCulloch</h1>
            <ul className="flex items-center">
              <li className="mr-4">
                <DarkModeSwitcher darkMode={darkMode} setDarkMode={setDarkMode} />
              </li>
              <li className="text-4xl mr-4">
                <a href="https://github.com/DavidMcCulloch98" target="_blank">
                  <FaGithub />
                </a>
              </li>
              <li className="text-4xl">
                <a href="https://www.linkedin.com/in/david-mcculloch-64277b178/" target="_blank">
                  <FaLinkedin />
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">David McCulloch</h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">Front-end Developer</h3>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-72 h-72 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={profile} layout="fill" objectFit="cover" />
            </div>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">Skilled React developer with a passion for solving problems. I enjoy rising to meet new challenges, always endeavouring to write clean, maintainable code.</p>
          </div>
        </section>
        <section>
          <div className="text-center p-8">
            <h2 className="text-3xl py-1 dark:text-white">Development Experience</h2>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Text to be added here: <span className="text-teal-500">Sky </span> and <span className="text-teal-500">FDM </span>
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-xl p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={sky} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2">Sky - React Developer</h3>
              <p className="py-2">During my time here I</p>
              <h4 className="py-4 text-teal-600">Job Responsibilites and Achievements</h4>
              <ul>
                <li className="text-gray-800 py-1">Point 1</li>
                <li className="text-gray-800 py-1">Point 2</li>
                <li className="text-gray-800 py-1">Point 3</li>
                <li className="text-gray-800 py-1">Point 4</li>
              </ul>
            </div>
            <div className="text-center shadow-xl p-10 rounded-xl lg:my-10 sm:py-6 dark:bg-white flex-1">
              <Image src={fdm} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2">FDM - Software Development Consultant</h3>
              <p className="py-2">During my time here I</p>
              <h4 className="py-4 text-teal-600">Job Responsibilites and Achievements</h4>
              <ul>
                <li className="text-gray-800 py-1">Point 1</li>
                <li className="text-gray-800 py-1">Point 2</li>
                <li className="text-gray-800 py-1">Point 3</li>
                <li className="text-gray-800 py-1">Point 4</li>
              </ul>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
